version: "3.9"

volumes:
  telegram_bot_data:
    driver: local

services:
  postgres:
    image: postgres:15
    volumes:
      - telegram_bot_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
