create table if not exists users
(
    id             bigint generated by default as identity,
    user_id        bigint                                 not null,
    cryptocurrency jsonb                                  not null,
    threshold      float4                                 not null,
    created_at     timestamp with time zone default now() not null,
    updated_at     timestamp with time zone default now() not null,
    constraint pk_id primary key (id)
);
